### ISSUE TITLE
How to model Chinese characters

### ISSUE THREAD

**Issue by jmliu88** [clovaai/dmfont#1]
Hi,

Nice work! 

I'm curious about how to extend DMfont to scripts like Chinese chars, which the number of compositional sub-glyphs for different chars differs. For example, “虾” can be decomposed as "⿰虫下", where are two sub-glyphs. However, the composition of “赢” looks like "⿱吂⿲月贝凡", which are four sub-glyphs. 

As I understood, the decoder in DMFont can only model a fixed number of sub-glyphs(3 in the paper). Could you plz give some idea about how to extend the model to Chinese or how to design the decomposition rule of Chinese?

Thanks,
James

**Comment by khanrc** [comment]
Hi,
Thanks to interest about our work.

Recently, we published LF-Font, which is the extension to Chinese chars. We simply average the features to handle the variable number of sub-glyphs. We also proposed conditional style encoder, factorization module, and content encoder in the extension.

Please refer to [paper](https://arxiv.org/abs/2009.11042) and [code](https://github.com/clovaai/lffont) for more details.

**Comment by jmliu88** [comment]
Awesome! Thanks for your reply.
