### ISSUE TITLE
ask for font ttf files

### ISSUE THREAD

**Issue by napCC** [clovaai/dmfont#2]
Hi, there!

Nice work and thank you for sharing the repo.

Can you please provide the font ttf files? 

thanks!

**Comment by khanrc** [comment]
As mentioned in the README, you can download the ttf files from [UhBee fonts](http://uhbeefont.com/) for Korean and [Thai font collection](https://github.com/jeffmcneill/thai-font-collection) for Thai.

**Comment by napCC** [comment]
Thanks!
