### ISSUE TITLE
could not get dataset 

### ISSUE THREAD

**Issue by XuyangPan** [clovaai/dmfont#7]
Hello,
could you provide a valid link available to get  UhBee fonts？

look forward to your replay.

**Comment by SanghyukChun** [comment]
Hi, you can find the link at README: https://github.com/clovaai/dmfont#data-sources
You can download the fonts by clicking yellow buttons

**Comment by XuyangPan** [comment]
after clicking the 'http://uhbeefont.com/'

![image](https://user-images.githubusercontent.com/39898699/122313451-d4d11800-cf48-11eb-8397-dd8a0c57af85.png)

**Comment by khanrc** [comment]
It is the working link. I think access to the link is prohibited in your place, so please try again through a proxy. If this option is not available, you can also get the relevant ttf files [here](https://drive.google.com/file/d/1ZapI77QpkwmG52Y9BeY86VLhjJeuo2s7/view?usp=sharing) instead (Note that these files are collected independently from this study and may differ from the version used in this study.).

**Comment by XuyangPan** [comment]
many thanks.
