### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by XuyangPan** [clovaai/dmfont#8]
Hello, excuse me
about meta/thai_split.json
'chars' represents available chars of union or intersection of all fonts ?  

could you explain detail the meaning of keys in *.json file ?

many thanks.

**Comment by khanrc** [comment]
It is made by intersection (as I recall).
The structure of meta `.json` file is:
```
{
  'train': {
    'fonts': [],
    'chars': []
  },
  'valid': {
    'fonts': [],
    'chars': []
  }
}
```
`train` and `valid` indicate training and validation sets, and `fonts` and `chars` are font names and characters used for each training/validation phase.

**Comment by XuyangPan** [comment]
Thanks for your kind reply.

What about parameter ‘img_dir’ in evaluator.py? 

For your convenience,  please talk about directory structure, image size, image channel and etc.

Best wishes, kind regards.

**Comment by khanrc** [comment]
Sorry for the late reply. The `img_dir` specifies the directory path where the generated images are saved.
